app/getguide_account/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'account'


urlpatterns = [
    path('signup/',register, name='register'),
    path('login/', login_view, name="login"),
    path('sent/',activation_sent, name="activation_sent"),
    path('logout/',logout_view,name='logout'),
    path('activated/',activated_view, name="activated"),
    path('finish_1',first_finish_view, name="finish_1"),
    path('finish_2',second_finish_view, name="finish_2"),
    path('finish_3',third_finish_view, name="finish_3"),
    path('finish_sucess',finish_success, name="finish_success"),
    path('myProfile', my_profile, name='my_profile'),
    path('forgot_password',forgot_password,name="forgot_password"),
    path("add_busy_date/", BusyDateView.as_view({'post': 'create',}), name="add_busy_date"),
    path("show_busy_date/", UserBusyDateView.as_view({'get': 'list',}), name="show_busy_date"),
    path("show_busy_date/<pk>/", UserBusyDateView.as_view({'get': 'retrieve',}), name="show_busy_date_detail"),



    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

app/product/urls.py
from django.urls import path, include
from .views import *

app_name = 'product'


urlpatterns = [
    path('', index, name='index'),
    path('faq/', Faq, name='faq'),
    path('about/',About,name="about"),
    path('blogs/',BlogView,name="blogs"),
    path('search_results/',SearchResults,name="search_results"),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('getguide_account.urls')),
    path('',include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView

# urlpatterns = [
#     #...
#     path('', TemplateView.as_view(template_name="index.html")),
#     path('accounts/', include('allauth.urls')),
#     path('logout', LogoutView.as_view()),
# ]

app/templates/login/forgot_password.html
{% extends 'base.html' %}
{% load static %}

<script src="https://www.google.com/recaptcha/enterprise.js?render=6LfKrFglAAAAALH7xTDjm5925HBG6FW3QYKPtRCj"></script>
<script>

{% block body %}




<div class="forgotPassContainer">
    <h3>Forgot Password</h3>
    <p>Enter your email address to update your password.</p>

      <div class="emailInput">
        <label for="emailForReset"><p>Email</p></label>
        <input type="text" id="emailForReset" placeholder="example@gmail.com" />
      </div>

      <div class="captcha">

        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="myBtn">Send</button>
      </form>
      </div>




  </div>



{% endblock body %}

app/templates/login/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="signup-container">
      <div class="signUpInner">
        <div class="signup-heading login-heading">
          <p>Login</p>
          <p>Hello again!</p>
        </div>

        <div class="signup-main guideSide">

          <div class="sign-borders">
            <div class="sign-border"></div>
            {% comment %} <p>or</p> {% endcomment %}
            <div class="sign-border"></div>
          </div>
          <form method="POST">
            {% csrf_token %}
            <div class="signup-inputs">
              <div class="signup-input">
                <label for="loginEmail"><p>Email</p></label>
                {{form.email|as_crispy_field}}
              </div>
              <div class="signup-input">
                <label for="loginPass"><p>Password</p></label>
                {{form.password|as_crispy_field}}
              </div>
            </div>

            <div class="signup-terms login-forgotPass">
              <a href="{% url 'account:forgot_password' %}">Forgot password?</a>
            </div>
            <div class="signUpBtn">
              <button class="myBtn">Log in</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    {% endblock body %}