app/getguide_account/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'account'


urlpatterns = [
    path('signup/',register, name='register'),
    path('login/', login_view, name="login"),
    path('sent/',activation_sent, name="activation_sent"),
    path('logout/',logout_view,name='logout'),
    path('activated/',activated_view, name="activated"),
    path('finish_1',first_finish_view, name="finish_1"),
    path('finish_2',second_finish_view, name="finish_2"),
    path('finish_3',third_finish_view, name="finish_3"),
    path('finish_sucess',finish_success, name="finish_success"),
    path('myProfile', my_profile, name='my_profile'),
    path('forgot_password',forgot_password,name="forgot_password"),
    path("add_busy_date/", BusyDateView.as_view({'post': 'create',}), name="add_busy_date"),
    path("show_busy_date/", UserBusyDateView.as_view({'get': 'list',}), name="show_busy_date"),
    path("show_busy_date/<pk>/", UserBusyDateView.as_view({'get': 'retrieve',}), name="show_busy_date_detail"),



    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

app/product/urls.py
from django.urls import path, include
from .views import *

app_name = 'product'


urlpatterns = [
    path('', index, name='index'),
    path('faq/', Faq, name='faq'),
    path('about/',About,name="about"),
    path('blogs/',BlogView,name="blogs"),
    path('search_results/',SearchResults,name="search_results"),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('getguide_account.urls')),
    path('',include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView

# urlpatterns = [
#     #...
#     path('', TemplateView.as_view(template_name="index.html")),
#     path('accounts/', include('allauth.urls')),
#     path('logout', LogoutView.as_view()),
# ]

app/templates/activation_after_login/finish_1.html
{% extends 'base_activation.html' %}
{% load static %}


{% block body %}
    <div class="accVerifyContainer">
      <div class="accVerifyInner">
        <h1>Account Verification</h1>

        <div class="successLine">
            <span id="twentyFive"></span>
            <span id="fifty"></span>
            <span id="seventyFive"></span>
        </div>

        <div class="verifyStep firstStep">
          <h3>Welcome!</h3>
          <p>
            Forem ipsum dolor sit amet, consectetur adipiscing elit. Nunc
            vulputate libero et velit interdum, ac aliquet odio mattis. Class
            aptent taciti sociosqu ad litora torquent per conubia nostra, per
            inceptos himenaeos. Curabitur tempus urna at turpis condimentum
            lobortis.
          </p>
          <form action="">
            <a href="{% url 'account:finish_2' %}" class="myBtn prevBtn">Start Filling Information</a>
          </form>
        </div>

      </div>
    </div>


    {% endblock body %}

app/templates/activation_after_login/finish_2.html
{% extends 'base_activation.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="accVerifyContainer">
      <div class="accVerifyInner">
        <h1>Account Verification</h1>

        <div class="successLine dash2">
            <span id="twentyFive"></span>
            <span id="fifty"></span>
            <span id="seventyFive"></span>
        </div>

        <div class="verifyStep secondStep">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <label
              ><p>First name</p>
              {{form.first_name|as_crispy_field}}
            </label>

            <label
              ><p>Last name</p>
              {{form.last_name|as_crispy_field}}
            </label>

            {% comment %} <label
              ><p>Location</p>
              <input type="text" placeholder="EX: Baku, Azerbaijan" />
            </label> {% endcomment %}

            <div class="secondBottom">
                <div class="uploadVideo">
                    <p>Upload ID Image</p>
                    <div class="addVideoFile">
                      {{form.id_image|as_crispy_field}}
                      <label for="file">Upload ID Image</label>
                    </div>
                  </div>
                  <p>Horem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet  odio mattis. Class</p>
            </div>
            <div class="stepButtons">
              <a href="{% url 'account:finish_1' %}" class="myBtn prevBtn">Previous</a>
              <button class="myBtn nextBtn">Next</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    {% endblock body %}

app/templates/activation_after_login/finish_3.html
{% extends 'base_activation.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="accVerifyContainer">
      <div class="accVerifyInner">
        <h1>Account Verification</h1>

        <div class="successLine dash3">
            <span id="twentyFive"></span>
            <span id="fifty"></span>
            <span id="seventyFive"></span>
        </div>


        <div class="verifyStep thirdStep">
          <form method="POST">
            {% csrf_token %}
            <div class="thirdTop">
              <p>Add identification photo</p>
              <div class="addFile">
                <input
                  class="hiden"
                  type="file"
                  id="file"
                  name="img"
                  accept="image/*"
                />
                <label for="file">Upload Photo</label>
              </div>
            </div>

            <div class="thirdBottom">
              {% comment %} <label>
                <p>Postal ID</p>
                <input type="text" placeholder="EX: AZ5000" />
              </label> {% endcomment %}

              <label>
                <p>Language</p>
                {{form.languages|as_crispy_field}}
              </label>

              <label>
                <p>Region</p>
                {{form.regions|as_crispy_field}}
              </label>

              <label id="numInputLabel">
                <p>Phone Number</p>
                <div class="numberInput">
                  <div class="countriesOptions">
                    {% comment %} <img src="./images/numbers/aze.png" alt="" /> {% endcomment %}
                    {% comment %} <i class="fa-regular fa-chevron-down"></i> {% endcomment %}
                  </div>
                  {{form.phone|as_crispy_field}}
                </div>
              </label>
            </div>
            <div class="stepButtons">
              <a href="./dashboard2.html" class="myBtn prevBtn">Previous</a>
              <button class="myBtn nextBtn">Submit</button>
            </div>
          </form>
        </div>

      </div>
    </div>

    <script src="./JS/accVerify.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
    <script>
      new MultiSelectTag('languages')
      new MultiSelectTag('regions')
  </script>


{% endblock body %}

app/templates/activation_after_login/finish_success.html
{% extends 'base_activation.html' %}
{% load static %}

{% block body %}

    <div class="accVerifyContainer">
      <div class="accVerifyInner">
        <h1>Account Verification</h1>

        <div class="successLine dash4">
            <span id="twentyFive"></span>
            <span id="fifty"></span>
            <span id="seventyFive"></span>
        </div>

        <div class="fourthStep">
            <div class="succesFullModal">
                <img src="{% static './images/successTick.png' %}" alt="">
                <h1>Your request has been successfully sent to us!</h1>
                <p>We will inform you after activation of your account</p>
                <a href="{% url 'product:index' %}" class="myBtn">Main Page</a>
              </div>
        </div>
      </div>
    </div>

    {% endblock body %}