app/getguide_account/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'account'


urlpatterns = [
    path('signup/',register, name='register'),
    path('login/', login_view, name="login"),
    path('sent/',activation_sent, name="activation_sent"),
    path('logout/',logout_view,name='logout'),
    path('activated/',activated_view, name="activated"),
    path('finish_1',first_finish_view, name="finish_1"),
    path('finish_2',second_finish_view, name="finish_2"),
    path('finish_3',third_finish_view, name="finish_3"),
    path('finish_sucess',finish_success, name="finish_success"),
    path('myProfile', my_profile, name='my_profile'),
    path('forgot_password',forgot_password,name="forgot_password"),
    path("add_busy_date/", BusyDateView.as_view({'post': 'create',}), name="add_busy_date"),
    path("show_busy_date/", UserBusyDateView.as_view({'get': 'list',}), name="show_busy_date"),
    path("show_busy_date/<pk>/", UserBusyDateView.as_view({'get': 'retrieve',}), name="show_busy_date_detail"),



    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

app/product/urls.py
from django.urls import path, include
from .views import *

app_name = 'product'


urlpatterns = [
    path('', index, name='index'),
    path('faq/', Faq, name='faq'),
    path('about/',About,name="about"),
    path('blogs/',BlogView,name="blogs"),
    path('search_results/',SearchResults,name="search_results"),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('getguide_account.urls')),
    path('',include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView

# urlpatterns = [
#     #...
#     path('', TemplateView.as_view(template_name="index.html")),
#     path('accounts/', include('allauth.urls')),
#     path('logout', LogoutView.as_view()),
# ]

app/templates/signup/account_activate.html
{% load static %}
{% autoescape off %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- <link rel="stylesheet" href="./CSS/style.css"> -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <style>
      a {
        transition: 0.3s;
        color: white;
        background-color: #3366ff;
        padding: 16px 99px;
        border-radius: 8px;
        border: 1px solid transparent;
      }
      a:hover {
        background-color: #ffffff;
        color: #3366ff;
        border-color: #3366ff;
      }
      section{
        box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
      }
    </style>
  </head>
  <body>
    <section
      class="verifyPageContainer"
      style="

        width: 50%;
        font-family: 'Open Sans', sans-serif;
        font-weight: 600;
      "
    >
      <div class="verifyContent" style="padding: 20px">
        <div
          class="verifyContentLogo"
          style="
            border-bottom: 1px solid #e4e9f2;
            padding-bottom: 30px;
            width: 40%;
          "
        >
          <img
            src="cid:Logo.png"
            alt=""
          />
        </div>
        <div class="verifyTexts" style="margin-bottom: 40px">
          <p>Welcome {{user.first_name}} {{user.last_name}}!</p>
          <p>Thank you for registering</p>
          <p>
            Almost there. Please click the button and <a href="" style="padding: 0; text-decoration: none; border-radius: 0; background-color: transparent; color: #3366ff; border: 0;">verify</a> your email address
            acount.
          </p>
        </div>
        <a href="http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}" style="text-decoration: none">VERIFY EMAIL ADRESS</a>
        <div
          class="verifyFooter"
          style="display: flex; align-items: center; margin-top: 60px"
        >
          <i
            class="fa-light fa-copyright"
            style="margin-right: 7px; font-size: 14px; color: #3e4b6c"
          ></i>
          <p style="font-size: 14px; color: #3e4b6c">
            2022 Getguide all rights reserved
          </p>
        </div>
      </div>
    </section>
  </body>
</html>
{% endautoescape %}

app/templates/signup/activated.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <link rel="stylesheet" href="{% static './CSS/style.css' %}" />
  </head>
  <body>
    <div class="main-header">
      <div class="total container">
        <div class="left-nav">
          <div class="logo">
            <a href="./index.html"
              ><img src="{% static './images/Logo.png' %}" alt="loqo"
            /></a>
          </div>
          <ul class="main-nav whiteNav successPage">
            <li><a href="./guides.html">Tour Guides</a></li>
            <!-- <li><a href="#">Partners</a></li> -->
            <li><a href="./blogs.html">Blogs</a></li>
            <li><a href="./about.html">About Us</a></li>
            <li class="FAQ">
              <a href="./faq.html"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </li>
          </ul>
        </div>
        <div class="main-right-nav successPage">
          <div class="main-lang">
            Az
            <i class="fa-solid fa-chevron-down"></i>
          </div>
          <a href="./login.html">Log in</a>
          <button class="main-sign">
            <a href="./signup.html">Sign Up</a>
          </button>
        </div>
      </div>
    </div>

    <div class="signup-container clickActivationPage">
      <div class="succesFullModal">
        <img src="{% static './images/successTick.png' %}" alt="">
        <h1>Your account has been successfully activated!</h1>
        <p>You can log in to your account</p>
        <button class="myBtn"><a href="{% url 'account:login' %}">Log in </a></button>
      </div>
    </div>
  </body>
</html>

app/templates/signup/activation_sent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <link rel="stylesheet" href="{% static './CSS/style.css' %}" />
  </head>
  <body>
    <div class="main-header">
      <div class="total container">
        <div class="left-nav">
          <div class="logo">
            <a href="{% url 'product:index' %}"
              ><img src="{% static './images/Logo.png' %}" alt="loqo"
            /></a>
          </div>
          <ul class="main-nav whiteNav">
            <li><a href="./guides.html">Tour Guides</a></li>
            <!-- <li><a href="#">Partners</a></li> -->
            <li><a href="./blogs.html">Blogs</a></li>
            <li><a href="./about.html">About Us</a></li>
            <li class="FAQ">
              <a href="./faq.html"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </li>
          </ul>
        </div>
        <div class="main-right-nav">
          <div class="main-lang">
            Az
            <i class="fa-solid fa-chevron-down"></i>
          </div>
          <a href="{% url 'account:login' %}">Log in</a>
          <button class="main-sign">
            <a href="{% url 'account:register' %}">Sign Up</a>
          </button>
        </div>
      </div>
    </div>

    <div class="signup-container clickActivationPage">
        <div class="clickActivationModal">
            <h1>Please click the activation link we sent to your email</h1>
            <p>An email has been sent to your email address containing an activation link. <br> Please click on the link to activate your account. <br> If you do not receive the email within a few minutes, please check your spam folder.</p>
        </div>
    </div>

  </body>
</html>

app/templates/signup/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="signup-container">
      <div class="signUpInner">
        <div class="signup-heading">
          <p>Sign up</p>
        </div>

        <div class="signup-main guideSide">
          
          <div class="sign-borders">
            <div class="sign-border"></div>
            <p>or</p>
            <div class="sign-border"></div>
          </div>
          <form method="POST">
            {% csrf_token %}
            <div class="signup-inputs">
              <div class="signup-input">
                <label for="signUpName"><p>Email</p></label>
                {{form.email|as_crispy_field}}
              </div>
              <div class="signup-input">
                <label for="signUpEmail"><p>Password1</p></label>
                {{form.password1|as_crispy_field}}
              </div>
              <div class="signup-input">
                <label for="signUpPass"><p>Password2</p></label>
                {{form.password2|as_crispy_field}}
              </div>
            </div>
            <div class="signAs browsers" >
              <h3>Sign up as:</h3>

              <ul>
                <li>
                  <input class="checkboxes" type="checkbox" id="guide" name="guide" required/>
                  <label for="guide">Guide</label>
                </li>
                <li>
                  <input class="checkboxes" type="checkbox" id="company" name="company" required/>
                  <label for="company">Company</label>
                </li>
                <li>
                  <input class="checkboxes" type="checkbox" id="driver" name="driver" required/>
                  <label for="driver">Driver</label>
                </li>
              </ul>
            </div>
            <div class="signup-terms">
              <p>
                By signing up, you agree with <a>Terms</a> and
                <a href="">Conditions</a>
              </p>
            </div>
            <div class="signUpBtn">
              <button class="myBtn" type="submit">Sign up</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    {% endblock body %}