app/getguide_account/urls.py
from django.urls import path,re_path
from .views import *

app_name = 'account'


urlpatterns = [
    path('signup/',register, name='register'),
    path('login/', login_view, name="login"),
    path('sent/',activation_sent, name="activation_sent"),
    path('logout/',logout_view,name='logout'),
    path('activated/',activated_view, name="activated"),
    path('finish_1',first_finish_view, name="finish_1"),
    path('finish_2',second_finish_view, name="finish_2"),
    path('finish_3',third_finish_view, name="finish_3"),
    path('finish_sucess',finish_success, name="finish_success"),
    path('myProfile', my_profile, name='my_profile'),
    path('forgot_password',forgot_password,name="forgot_password"),
    path("add_busy_date/", BusyDateView.as_view({'post': 'create',}), name="add_busy_date"),
    path("show_busy_date/", UserBusyDateView.as_view({'get': 'list',}), name="show_busy_date"),
    path("show_busy_date/<pk>/", UserBusyDateView.as_view({'get': 'retrieve',}), name="show_busy_date_detail"),



    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        activate, name='activate'),
]

app/product/urls.py
from django.urls import path, include
from .views import *

app_name = 'product'


urlpatterns = [
    path('', index, name='index'),
    path('faq/', Faq, name='faq'),
    path('about/',About,name="about"),
    path('blogs/',BlogView,name="blogs"),
    path('search_results/',SearchResults,name="search_results"),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('getguide_account.urls')),
    path('',include('product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# from django.urls import path, include
# from django.views.generic import TemplateView
# from django.contrib.auth.views import LogoutView

# urlpatterns = [
#     #...
#     path('', TemplateView.as_view(template_name="index.html")),
#     path('accounts/', include('allauth.urls')),
#     path('logout', LogoutView.as_view()),
# ]

app/templates/base_activation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
    <link rel="stylesheet" href="{% static './CSS/style.css' %}" />
  </head>
  <body>
    <div class="main-header">
      <div class="total container">
        <div class="left-nav">
          <div class="logo">
            <a href="/"><img src="{% static './images/Logo.png' %}" alt="loqo" /></a>
          </div>
          <ul class="main-nav whiteNav">
            <li><a href="./guides.html">Tour Guides</a></li>
            <!-- <li><a href="#">Partners</a></li> -->
            <li><a href="./blogs.html">Blogs</a></li>
            <li><a href="./about.html">About Us</a></li>
            <li class="FAQ">
              <a href="./faq.html"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </li>
          </ul>
        </div>
        <div class="main-right-nav">
          <div class="main-lang">
            Az
            <i class="fa-solid fa-chevron-down"></i>
          </div>
          <div class="headerProfile">
            <img src="{{request.user.get_avatar}}" alt="" />
          </div>
        </div>
      </div>
    </div>

{% block body %}

{% endblock body %}



</body>
</html>

app/templates/blogs.html
{% extends 'base.html' %} {% load static %} {% block body %}

<section class="breadcrumbs blogsPage">
  <div class="breadcrumb myWrapper">
    <p>Home</p>
    <i class="fa-solid fa-chevron-right"></i>
    <p>Blogs</p>
  </div>
  <div class="breadcrumbs-text myWrapper">
    <p>Blogs</p>
  </div>
</section>

<div class="ourBlog blogsPage myWrapper">
  <div class="blogs">
    {% for blog in blogs %}
    <!-- One Blog  -->
    <div class="oneBlog">
      <div class="blogImg">
        <img src="{{blog.image.url}}" alt="" />
      </div>
      <div class="blogContent">
        <h1>Help your team transition to remote with this essential guide</h1>
      </div>
      <p class="blogDate">31 iyul, 2021</p>
    </div>
    <!-- One Blog End -->
    {% endfor %}
  </div>

  <div class="paginationContainer">
    <ul class="pagination">
      <i class="fa-regular fa-chevron-left"></i>
      <div class="pagNumbers">
        <li>1</li>
        <li>2</li>
        <li class="active">3</li>
        <li>4</li>
        <li>...</li>
        <li>12</li>
      </div>
      <i class="fa-regular fa-chevron-right"></i>
    </ul>
  </div>

  {% endblock body %}
</div>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if user.is_authenticated %}
    <meta name="csrf-token" content="{{ csrf_token }}" />
    {% endif %}

    <title>Document</title>
    <link rel="stylesheet" href="{% static './CSS/style.css' %}" />
    <link rel="stylesheet" href="{% static './CSS/responsive.css' %}" />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css"
    />
    <link rel="stylesheet" href="{% static './CSS/guideRegion.css' %}" />
  </head>
  <body>
    <!-- Header Start -->
    <header>
      <div class="total container">
        <div class="left-nav">
          <div class="logo">
            <a href="./index.html"
              ><img src="{% static './images/whitelogo.png' %}" alt="loqo"
            /></a>
          </div>
          <ul class="nav whiteNav homeNav">
            <li>
              <a href="{% url 'product:search_results' %}">Search Results</a>
            </li>

            <!-- <li><a href="#">Partners</a></li> -->
            <li><a href="{% url 'product:blogs' %}">Blogs</a></li>
            <li><a href="{% url 'product:about' %}">About Us</a></li>
            <li class="FAQ">
              <a href="{% url 'product:faq' %}"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </li>
          </ul>
        </div>
        <ul class="right-nav">
          <div class="main-right-nav">
            <div class="main-lang">
              Az
              <i class="fa-solid fa-chevron-down"></i>
            </div>
            {% if request.user.is_authenticated %}
            <div class="headerProfile">
              <a href="{% url 'account:my_profile' %}">
                <img src="{{request.user.get_avatar}}" alt="" />
              </a>
            </div>
            {% else %}
            <a href="{% url 'account:login' %}">Log in</a>
            <button class="sign">
              <a href="{% url 'account:register' %}">Sign Up</a>
            </button>
            {% endif %}
          </div>
        </ul>
      </div>
    </header>
    <!-- Header End -->

    <!-- Section 1 Start  -->
    <section class="hero">
      <div class="container">
        <div class="hero-total">
          <!-- <img class="busImage" src="../static/images/bus.png" alt="" /> -->
          <img class="busImage" src="../static/images/prius.png" alt="" />
          <div class="hero-text">
            <h1>Lorem ipsum dolor sit amet mamed</h1>
          </div>
          <div class="userSelectBtns">
            <button id="guideBtn" class="myBtn selectedBtn">GUIDE</button>
            <button id="driverBtn" class="myBtn">DRIVER</button>
          </div>
          <form class="heroInputs forGuide">
            <label class="heroInput">
              <i class="fa-sharp fa-light fa-house-tree fa-lg"></i>
              <select class="regionSelect" name="regions" id="regions" multiple>
                <option value="agsu">Agsu</option>
                <option value="shabran">Shabran</option>
                <option value="goranboy">Goranboy</option>
                <option value="hajiqabul">Hajiqabul</option>
                <option value="masally">Masally</option>
                <option value="gobustan">Gobustan</option>
              </select>
            </label>
            <label for="" class="heroInput">
              <i class="fa-sharp fa-solid fa-globe"></i>
              <select
                class="langSelect"
                name="languages"
                id="languages"
                multiple
              >
                <option value="english">English</option>
                <option value="azerbaijan">Azerbaijan</option>
                <option value="russian">Russian</option>
                <option value="spanish">Spanish</option>
                <option value="french">French</option>
                <option value="arabic">Arabic</option>
                <option value="bengali">Bengali</option>
              </select>
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-calendar-days fa-lg"></i>
              <input type="date" placeholder="Date" />
            </label>
            <button class="myBtn">Search</button>
          </form>
          <div class="heroInputs forDriver none">
            <label class="heroInput">
              <i class="fa-sharp fa-light fa-house-tree fa-lg"></i>
              <input type="text" placeholder="Region" />
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-users"></i>
              <input type="number" placeholder="Number of people" />
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-calendar-days fa-lg"></i>
              <input type="date" placeholder="Date" />
            </label>
            <button class="myBtn">Search</button>
          </div>
        </div>
      </div>
    </section>
    <!-- Section 1 End  -->

    <!-- Section 2 Start  -->
    <section class="achievements">
      <div class="pink"></div>
      <div class="green"></div>
      <div class="yellow"></div>
      <div class="heading">
        <h2>Our achievements</h2>
        <p>
          As in business, we believe that competition encourages innovation.
        </p>
      </div>
      <div class="container">
        <div class="achieves">
          <img id="line1" src="{% static './images/line1.png' %}" alt="" />
          <img id="line2" src="{% static './images/line2.png' %}" alt="" />
          <img id="line3" src="{% static './images/line3.png' %}" alt="" />
          <div class="achieve">
            <!-- <img src="./images/line1.png" alt=""> -->
            <div id="burst-8"></div>
            <h2 class="blue">78</h2>
            <p>Guides</p>
            <!-- <div class="right-border"></div> -->
          </div>
          <div class="achieve">
            <div id="burst-8"></div>
            <h2 class="eight">870</h2>
            <p>Travelers</p>
            <!-- <div class="right-border"></div> -->
          </div>
          <div class="achieve">
            <!-- <img src="./images/line1.png" alt=""> -->
            <div id="burst-8"></div>
            <h2 class="eight">870</h2>
            <p>Travelers</p>
            <!-- <div class="right-border"></div> -->
          </div>
          <div class="achieve">
            <div id="burst-8"></div>
            <h2 class="three">34</h2>
            <p>Partners</p>
          </div>
        </div>
      </div>
    </section>
    <!-- Section 2 End  -->

    <!-- Section 3 Start  -->
    {% comment %}
    <section class="Guides">
      <div class="container">
        <div class="heading">
          <h2>Our Guides</h2>
        </div>
        <div class="guides">
          {% for guide in guides %}
          <div class="one-guide">
            <div class="guide-image">
              <img src="{% static './images/test.webp' %}" />
            </div>

            <div class="guide-text">
              <div class="guide-top-text">
                <p>{{guide.first_name}} {{guide.last_name}}</p>
                <p>
                  Manage simple to complex projects across multiple teams,
                  departments
                </p>
              </div>
              <div class="guide-bottom-text">
                <p>20,99<span>₼</span></p>

                <p>23 Reviews</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div id="all" class="forBtn">
          <a href="./guides.html">See All</a
          ><i class="fa-solid fa-angle-right"></i>
        </div>
      </div>
    </section>
    {% endcomment %}
    <!-- Section 3 End  -->

    <!-- Section 4 Start  -->
    <section class="best-selling">
      <div class="container">
        <div class="selling">
          <div class="left-best-selling">
            <div class="pink-linear">
              <div class="best-video">
                <video controls>
                  <source
                    src="{% static './videos/testvideo.m4v' %}"
                    type="video/mp4"
                  />
                </video>
              </div>
            </div>
          </div>
          <div class="right-best-selling">
            <p>Best Selling Product of the month</p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quis sit
              sed at auctor lacus dictum amet aliquam cursus. Et purus quis
              accumsan at id vel ut quis sagittis.
            </p>
            <button class="sell-best">Get your guide</button>
          </div>
        </div>
      </div>
    </section>
    <!-- Section 4 End  -->

    <div class="ourBlog myWrapper">
      <h1>Our Blogs</h1>
      <div class="blogs">
        {% for blog in blogs|slice:':6' %}
        <!-- One Blog  -->
        <div class="oneBlog">
          <div class="blogImg">
            <img
              style="width: 486px; height: 349px; object-fit: cover"
              src="{{blog.image.url}}"
              alt=""
            />
          </div>
          <div class="blogContent">
            <h1>
              <a href="www.google.com"> {{blog.name}} </a>
            </h1>
          </div>
          <p class="blogDate">{{blog.created_date|date:"d M, Y"}}</p>
        </div>
        <!-- One Blog End -->
        {% endfor %}
      </div>
      <div class="forBtn">
        <a href="./blogs.html" id="addBlogs">
          See All <i class="fa-solid fa-angle-right"></i>
        </a>
      </div>
    </div>

    <div class="largestProgram myWrapper">
      <div class="largestHeader">
        <h1>Getguide is the world’s largest Program</h1>
      </div>
      <div class="largestProgramBody">
        <div class="largestBodyImg">
          <img src="{% static './images/largestProgramBg.png' %}" alt="" />
          <div class="textBox">
            <h1>The Impact Of The event Marketing</h1>
            <p>
              Only a quid it's all gone to pot say codswallop loo tinkety tonk
              old fruit Oxford Why, porkies cheeky bugger tickety-boo butty a
              load of old.
            </p>
            <button>Create a trip</button>
            <img
              class="circle"
              src="{% static './images/circle.png' %}"
              alt=""
            />
          </div>
        </div>
      </div>
    </div>

    <div class="footerContainer">
      <div class="footerBorders">
        <div class="footer myWrapper">
          <div class="foot1">
            <div class="foot1Logo">
              <a href="./index.html"
                ><img src="{% static './images/Logo.png' %}" alt=""
              /></a>
            </div>
            <div class="foot1Socials">
              <a href="" id="fb"
                ><i class="fa-brands fa-square-facebook"></i
              ></a>
              <a href="" id="insta"><i class="fa-brands fa-instagram"></i></a>
              <a href="" id="youtube"><i class="fa-brands fa-youtube"></i></a>
              <a href="" id="linkedin"><i class="fa-brands fa-linkedin"></i></a>
            </div>
          </div>
          <div class="foot2">
            <h2>Customer Care</h2>
            <p><a href="">Contact Us</a></p>
            <p><a href="">Size Guide</a></p>
            <p><a href="">My Order</a></p>
            <p><a href=""> My Account </a></p>
          </div>
          <div class="foot3">
            <h2>Shipping & Returns</h2>
            <p><a href="">Shipping</a></p>
            <p><a href="">Track Your Order</a></p>
            <p><a href="">Returns and exchanges</a></p>
            <p class="footerFaq">
              <a href="./faq.html"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </p>
          </div>
          <div class="foot4">
            <h2>Corporate</h2>
            <p><a href="">Careers</a></p>
            <p><a href="">Social Responsibility</a></p>
            <p><a href="">Reseller</a></p>
          </div>
        </div>
      </div>
      <div class="myWrapper">
        <div class="copyright">
          <i class="fa-light fa-copyright"></i>
          2022 Getguide all rights reserved
        </div>
      </div>
    </div>

    <script src="{% static './JS/app.js' %}"></script>
    <script src="{% static './JS/hero.js' %}"></script>

    <!-- Multi Languages  -->
    <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
    <script>
      new MultiSelectTag("languages");
      new MultiSelectTag("regions");
    </script>

    <script src="{% static './JS/guideRegion.js' %}"></script>
  </body>
</html>

app/templates/searchResults.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if user.is_authenticated %}
    <meta name="csrf-token" content="{{ csrf_token }}" />
    {% endif %}

    <title>Document</title>
    <link rel="stylesheet" href="{% static './CSS/style.css' %}" />
    <link rel="stylesheet" href="{% static './CSS/responsive.css' %}" />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://site-assets.fontawesome.com/releases/v6.2.1/css/sharp-solid.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css"
    />
    <link rel="stylesheet" href="{% static './CSS/guideRegion.css' %}" />
  </head>
  <body>
    <!-- Header Start -->
    <header>
      <div class="total container">
        <div class="left-nav">
          <div class="logo">
            <a href="./index.html"
              ><img src="{% static './images/whitelogo.png' %}" alt="loqo"
            /></a>
          </div>
          <ul class="nav whiteNav homeNav">
            <li>
              <a href="{% url 'product:search_results' %}">Search Results</a>
            </li>

            <!-- <li><a href="#">Partners</a></li> -->
            <li><a href="{% url 'product:blogs' %}">Blogs</a></li>
            <li><a href="{% url 'product:about' %}">About Us</a></li>
            <li class="FAQ">
              <a href="{% url 'product:faq' %}"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </li>
          </ul>
        </div>
        <ul class="right-nav">
          <div class="main-right-nav">
            <div class="main-lang">
              Az
              <i class="fa-solid fa-chevron-down"></i>
            </div>
            {% if request.user.is_authenticated %}
            <div class="headerProfile">
              <a href="{% url 'account:my_profile' %}">
                <img src="{{request.user.get_avatar}}" alt="" />
              </a>
            </div>
            {% else %}
            <a href="{% url 'account:login' %}">Log in</a>
            <button class="sign">
              <a href="{% url 'account:register' %}">Sign Up</a>
            </button>
            {% endif %}
          </div>
        </ul>
      </div>
    </header>
    <!-- Header End -->

    <!-- Section 1 Start  -->
    <section class="hero">
      <div class="container">
        <div class="hero-total">
          <!-- <img class="busImage" src="../static/images/bus.png" alt="" /> -->
          <img class="busImage" src="../static/images/prius.png" alt="" />
          <div class="hero-text">
            <h1>Lorem ipsum dolor sit amet mamed</h1>
          </div>
          <div class="userSelectBtns">
            <button id="guideBtn" class="myBtn selectedBtn">GUIDE</button>
            <button id="driverBtn" class="myBtn">DRIVER</button>
          </div>
          <form class="heroInputs forGuide">
            <label class="heroInput">
              <i class="fa-sharp fa-light fa-house-tree fa-lg"></i>
              <select class="regionSelect" name="regions" id="regions" multiple>
                <option value="agsu">Agsu</option>
                <option value="shabran">Shabran</option>
                <option value="goranboy">Goranboy</option>
                <option value="hajiqabul">Hajiqabul</option>
                <option value="masally">Masally</option>
                <option value="gobustan">Gobustan</option>
              </select>
            </label>
            <label for="" class="heroInput">
              <i class="fa-sharp fa-solid fa-globe"></i>
              <select
                class="langSelect"
                name="languages"
                id="languages"
                multiple
              >
                <option value="english">English</option>
                <option value="azerbaijan">Azerbaijan</option>
                <option value="russian">Russian</option>
                <option value="spanish">Spanish</option>
                <option value="french">French</option>
                <option value="arabic">Arabic</option>
                <option value="bengali">Bengali</option>
              </select>
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-calendar-days fa-lg"></i>
              <input type="date" placeholder="Date" />
            </label>
            <button class="myBtn">Search</button>
          </form>
          <div class="heroInputs forDriver none">
            <label class="heroInput">
              <i class="fa-sharp fa-light fa-house-tree fa-lg"></i>
              <input type="text" placeholder="Region" />
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-users"></i>
              <input type="number" placeholder="Number of people" />
            </label>
            <label class="heroInput">
              <i class="fa-solid fa-calendar-days fa-lg"></i>
              <input type="date" placeholder="Date" />
            </label>
            <button class="myBtn">Search</button>
          </div>
        </div>
      </div>
    </section>
    <!-- Section 1 End  -->

    <!-- Search Results Start  -->
    <section class="searchResults myWrapper">
      <div class="gdResults">
        <div class="gdCard">
          <div class="gdImg">
            <img src="../static/images/f1.jpg" alt="" />
          </div>
          <div class="gdContent">
            <div class="nameCont">
              <i class="fa-regular fa-user"></i>
              <span class="userName">Koti</span>
            </div>
            <div class="langCont">
              <i class="fa-light fa-globe"></i>
              <span class="userLang"
                >Englsih Russian Englsih Russian Azerbaijan
              </span>
            </div>
            <div class="rateCont">
              <i class="fa-solid fa-star"></i>
              <span class="userRate">4.5</span>
            </div>
          </div>
        </div>

        <div class="gdCard">
          <div class="gdImg">
            <img src="../static/images/f2.jpg" alt="" />
          </div>
          <div class="gdContent">
            <div class="nameCont">
              <i class="fa-regular fa-user"></i>
              <span class="userName">Koti</span>
            </div>
            <div class="langCont">
              <i class="fa-light fa-globe"></i>
              <span class="userLang"
                >Englsih Russian Englsih Russian Azerbaijan
              </span>
            </div>
            <div class="rateCont">
              <i class="fa-solid fa-star"></i>
              <span class="userRate">4.5</span>
            </div>
          </div>
        </div>

        <div class="gdCard">
          <div class="gdImg">
            <img src="../static/images/f3.jpg" alt="" />
          </div>
          <div class="gdContent">
            <div class="nameCont">
              <i class="fa-regular fa-user"></i>
              <span class="userName">Koti</span>
            </div>
            <div class="langCont">
              <i class="fa-light fa-globe"></i>
              <span class="userLang"
                >Englsih Russian Englsih Russian Azerbaijan
              </span>
            </div>
            <div class="rateCont">
              <i class="fa-solid fa-star"></i>
              <span class="userRate">4.5</span>
            </div>
          </div>
        </div>

        <div class="gdCard">
          <div class="gdImg">
            <img src="../static/images/f4.jpg" alt="" />
          </div>
          <div class="gdContent">
            <div class="nameCont">
              <i class="fa-regular fa-user"></i>
              <span class="userName">Koti</span>
            </div>
            <div class="langCont">
              <i class="fa-light fa-globe"></i>
              <span class="userLang"
                >Englsih Russian Englsih Russian Azerbaijan
              </span>
            </div>
            <div class="rateCont">
              <i class="fa-solid fa-star"></i>
              <span class="userRate">4.5</span>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- Search Results End  -->

    <div class="footerContainer">
      <div class="footerBorders">
        <div class="footer myWrapper">
          <div class="foot1">
            <div class="foot1Logo">
              <a href="./index.html"
                ><img src="{% static './images/Logo.png' %}" alt=""
              /></a>
            </div>
            <div class="foot1Socials">
              <a href="" id="fb"
                ><i class="fa-brands fa-square-facebook"></i
              ></a>
              <a href="" id="insta"><i class="fa-brands fa-instagram"></i></a>
              <a href="" id="youtube"><i class="fa-brands fa-youtube"></i></a>
              <a href="" id="linkedin"><i class="fa-brands fa-linkedin"></i></a>
            </div>
          </div>
          <div class="foot2">
            <h2>Customer Care</h2>
            <p><a href="">Contact Us</a></p>
            <p><a href="">Size Guide</a></p>
            <p><a href="">My Order</a></p>
            <p><a href=""> My Account </a></p>
          </div>
          <div class="foot3">
            <h2>Shipping & Returns</h2>
            <p><a href="">Shipping</a></p>
            <p><a href="">Track Your Order</a></p>
            <p><a href="">Returns and exchanges</a></p>
            <p class="footerFaq">
              <a href="./faq.html"
                >FAQ <i class="fa-light fa-comments-question"></i
              ></a>
            </p>
          </div>
          <div class="foot4">
            <h2>Corporate</h2>
            <p><a href="">Careers</a></p>
            <p><a href="">Social Responsibility</a></p>
            <p><a href="">Reseller</a></p>
          </div>
        </div>
      </div>
      <div class="myWrapper">
        <div class="copyright">
          <i class="fa-light fa-copyright"></i>
          2022 Getguide all rights reserved
        </div>
      </div>
    </div>

    <script src="{% static './JS/app.js' %}"></script>
    <script src="{% static './JS/hero.js' %}"></script>

    <!-- Multi Languages  -->
    <script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>
    <script>
      new MultiSelectTag("languages");
      new MultiSelectTag("regions");
    </script>

    <script src="{% static './JS/guideRegion.js' %}"></script>
  </body>
</html>